#include <iostream>
using namespace std;

#define MAX_LENGTH_SO_HIEU_MB 15
#define MAX_LENGTH_MA_CB 15
#define MAX_LENGTH_LOAI_MAY_BAY 40
#define MAX_MAYBAY 300
#define MAX_LENGTH_SAN_BAY_DEN 100
#define MAX_LENGTH_TIME 5
#define MAX_LENGTH_TIME_STRING 15
#define MAX_LENGTH_SO_CMND 15
#define MAX_LENGTH_HO 50
#define MAX_LENGTH_TEN 15
#define MAX_LENGTH_PHAI 100
#define MAX_LENGTH_SO_VE 4
#define MAX_LENGTH_ERROR_MESSAGE 100